version: '3'
services:

  #---- NOTIFICATIONS SERVICE [NodeJS] ----
  pub-notifications-db:
    image: postgres:15.2-alpine
    container_name: pub-notifications-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notifications_db
      POSTGRES_SSLMODE: disable
    ports:
      - "7008:5432"

  pub-notifications:
    build: ./pub-notifications
    container_name: pub-notifications
    depends_on:
      - pub-notifications-db
    restart: on-failure
    ports:
      - "7001:3000"
    environment:
      - DB_ENGINE=org.postgresql.Driver
      - DB_HOST=pub-notifications-db
      - DB_PORT=5432
      - DB_NAME=notifications_db
      - DB_USER=admin
      - DB_PASSWORD=admin


  # ---- USERS SERVICE [NodeJS] ----
  pub-users-db:
    image: postgres:15.2-alpine
    container_name: pub-users-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users-db
      POSTGRES_SSLMODE: disable
    ports:
      - "7002:5432"
  #  volumes:
  #    - ./pub-users-db/postgresql.conf:/etc/postgresql.conf
  #    - ./pub-users-db/pg-data:/var/lib/postgresql/data

  pub-users:
    build: ./pub-users
    container_name: pub-users
    depends_on:
      - pub-users-db
    restart: on-failure
    ports:
      - "7003:3000"
    environment:
      - POSTGRES_URI=postgres://admin:admin@pub-users-db:5432/users-db

  #---- PRODUCTS SERVICE [Quarkus] ----
  pub-products-db:
    image: mysql:8.0.32
    container_name: pub-products-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "7004:3306"
  #  volumes:
  #    - ./pub-products-db:/var/lib/mysql

  pub-products:
    build: ./pub-products
    container_name: pub-products
    depends_on:
      - pub-products-db
    restart: always
    ports:
      - "7005:8080"
    environment:
      DB_ENGINE: mysql
      DB_HOST: pub-products-db
      DB_PORT: 3306
      DB_NAME: products_db
      DB_USER: admin
      DB_PASSWORD: admin
    volumes:
      - ./pub-products/.m2:/.m2
      - ./pub-products/target:/work/target
      - ./pub-products/images:/deployments/images

  #---- FRONTEND SERVICE [React + Vite] ----
  pub-frontend:
    depends_on:
      - pub-products
      - pub-notifications
      - pub-users
    build: ./pub-frontend
    container_name: pub-frontend
    restart: on-failure
    ports:
      - "7006:5173"
      - "7007:3000"
